/*
SELECT <col> FROM <table>
ORDER BY <col> [ASC/DESC];
*/

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME)
FROM EMPLOYEES
ORDER BY CONCAT(FIRST_NAME, ' ', LAST_NAME) DESC;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME)
FROM EMPLOYEES
ORDER BY LENGTH(CONCAT(FIRST_NAME, ' ', LAST_NAME)) DESC;
