SELECT
	EXTRACT(YEAR FROM ORDERDATE) AS "Year",
	EXTRACT(MONTH FROM ORDERDATE) AS "Month",
	EXTRACT(DAY FROM ORDERDATE) AS "Day",
	SUM(OL.QUANTITY)
FROM ORDERLINES AS OL
GROUP BY
	ROLLUP(
		EXTRACT(YEAR FROM ORDERDATE),
		EXTRACT(MONTH FROM ORDERDATE),
		EXTRACT(DAY FROM ORDERDATE)
	)
ORDER BY
	EXTRACT(YEAR FROM ORDERDATE),
	EXTRACT(MONTH FROM ORDERDATE),
	EXTRACT(DAY FROM ORDERDATE);
