/*
*/
SELECT
	EMP_NO,
	COUNT(SALARY) OVER(
		ORDER BY EMP_NO		-- works like accumulative sum
		RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
	)
FROM SALARIES;

-- Find the current salary and compare it with the max salary
-- Employees
SELECT DISTINCT
	E.EMP_NO AS "EMP. ID",
	CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS "Full Name",
	D.DEPT_NAME AS "Department",
	LAST_VALUE(S.SALARY) OVER(
		PARTITION BY E.EMP_NO
		ORDER BY S.FROM_DATE
		RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
	) AS "Current Salary",
	MAX(S.SALARY) OVER(
		PARTITION BY E.EMP_NO
		ORDER BY S.FROM_DATE
		RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
	) AS "Max Salary"
FROM SALARIES AS S
INNER JOIN EMPLOYEES AS E USING(EMP_NO)
INNER JOIN DEPT_EMP AS DE USING(EMP_NO)
INNER JOIN DEPARTMENTS AS D USING(DEPT_NO)
ORDER BY E.EMP_NO;
