/*
- Create a VIEW:
    CREATE VIEW view_name AS query;
- Update a VIEW:
    CREATE OR REPLACE view_name AS query;
- Rename a VIEW:
    ALTER VIEW view_name RENAME TO new_view_name;
- Deleting a VIEW
    DROP VIEW [ IF EXISTS ] view_name;
*/

-- Example 1:
CREATE OR REPLACE VIEW GET_LAST_SALARY_CHANGED AS
SELECT DISTINCT
	E.EMP_NO,
	MAX(S.FROM_DATE) OVER(
		PARTITION BY E.EMP_NO
	) AS "last_salary_changed",
	S.SALARY
FROM EMPLOYEES AS E
INNER JOIN SALARIES AS S USING(EMP_NO);

---- Now use the view to get the last salary changed for each employee
SELECT *
FROM SALARIES AS L
INNER JOIN GET_LAST_SALARY_CHANGED AS LS USING(EMP_NO)
WHERE L.FROM_DATE = LS.LAST_SALARY_CHANGED
ORDER BY L.EMP_NO;

-- Example 2:
CREATE OR REPLACE VIEW GET_MAX_SALARY_GROUP_BY_EMP AS
SELECT DISTINCT
	E.EMP_NO,
	MAX(S.SALARY) OVER(
		PARTITION BY E.EMP_NO
	) AS "max_salary",
	S.FROM_DATE
FROM EMPLOYEES AS E
INNER JOIN SALARIES AS S USING(EMP_NO);


