-- DB: Store
SELECT
	C.FIRSTNAME, C.LASTNAME, C.INCOME
FROM CUSTOMERS AS C
WHERE EXISTS (
	SELECT *
	FROM ORDERS AS O
	WHERE C.CUSTOMERID = O.CUSTOMERID AND O.TOTALAMOUNT > 400
) AND C.INCOME > 90000;